{
  "cve_id": "CVE-2017-18184",
  "github_data": {
    "repository": "qpdf/qpdf",
    "fix_commit": "dea704f0ab7f625e1e7b3f9a1110b45b63157317",
    "related_commits": [
      "dea704f0ab7f625e1e7b3f9a1110b45b63157317",
      "dea704f0ab7f625e1e7b3f9a1110b45b63157317"
    ],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": null,
    "cvss_vector": null,
    "cwe_id": "CWE-125",
    "description": "An issue was discovered in QPDF before 7.0.0. There is a stack-based out-of-bounds read in the function iterate_rc4 in QPDF_encryption.cc.",
    "attack_vector": null,
    "attack_complexity": null
  },
  "temporal_data": {
    "published_date": "2018-02-13T19:29:00.370",
    "last_modified": "2024-11-21T03:19:30.217",
    "fix_date": null
  },
  "references": [
    {
      "url": "https://github.com/qpdf/qpdf/commit/dea704f0ab7f625e1e7b3f9a1110b45b63157317",
      "source": "cve@mitre.org",
      "tags": [
        "Patch",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://github.com/qpdf/qpdf/issues/147",
      "source": "cve@mitre.org",
      "tags": [
        "Issue Tracking",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://usn.ubuntu.com/3638-1/",
      "source": "cve@mitre.org",
      "tags": []
    },
    {
      "url": "https://github.com/qpdf/qpdf/commit/dea704f0ab7f625e1e7b3f9a1110b45b63157317",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Patch",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://github.com/qpdf/qpdf/issues/147",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Issue Tracking",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://usn.ubuntu.com/3638-1/",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": []
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T22:59:15.412196",
    "processing_status": "raw"
  }
}