{
  "cve_id": "CVE-2024-30799",
  "github_data": {
    "repository": "PX4/PX4-Autopilot",
    "fix_commit": null,
    "related_commits": [],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": 4.4,
    "cvss_vector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:N/I:N/A:H",
    "cwe_id": "CWE-120",
    "description": "An issue in PX4 Autopilot v1.14 and before allows a remote attacker to execute arbitrary code and cause a denial of service via the Breach Return Point function.",
    "attack_vector": "LOCAL",
    "attack_complexity": "HIGH"
  },
  "temporal_data": {
    "published_date": "2024-04-22T01:15:47.340",
    "last_modified": "2024-11-22T19:15:06.147",
    "fix_date": null
  },
  "references": [
    {
      "url": "https://github.com/PX4/PX4-Autopilot/issues/22428",
      "source": "cve@mitre.org",
      "tags": []
    },
    {
      "url": "https://github.com/PX4/PX4-Autopilot/issues/22428",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": []
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T23:08:07.004738",
    "processing_status": "raw"
  }
}