{
  "cve_id": "CVE-2014-3589",
  "github_data": {
    "repository": "python-pillow/Pillow",
    "fix_commit": "205e056f8f9b06ed7b925cf8aa0874bc4aaf8a7d",
    "related_commits": [
      "205e056f8f9b06ed7b925cf8aa0874bc4aaf8a7d",
      "205e056f8f9b06ed7b925cf8aa0874bc4aaf8a7d"
    ],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": null,
    "cvss_vector": null,
    "cwe_id": "CWE-20",
    "description": "PIL/IcnsImagePlugin.py in Python Imaging Library (PIL) and Pillow before 2.3.2 and 2.5.x before 2.5.2 allows remote attackers to cause a denial of service via a crafted block size.",
    "attack_vector": null,
    "attack_complexity": null
  },
  "temporal_data": {
    "published_date": "2014-08-25T14:55:06.643",
    "last_modified": "2024-11-21T02:08:27.560",
    "fix_date": null
  },
  "references": [
    {
      "url": "http://lists.opensuse.org/opensuse-updates/2015-04/msg00056.html",
      "source": "secalert@redhat.com",
      "tags": []
    },
    {
      "url": "http://secunia.com/advisories/59825",
      "source": "secalert@redhat.com",
      "tags": []
    },
    {
      "url": "http://www.debian.org/security/2014/dsa-3009",
      "source": "secalert@redhat.com",
      "tags": []
    },
    {
      "url": "https://github.com/python-pillow/Pillow/commit/205e056f8f9b06ed7b925cf8aa0874bc4aaf8a7d",
      "source": "secalert@redhat.com",
      "tags": [
        "Patch"
      ]
    },
    {
      "url": "https://pypi.python.org/pypi/Pillow/2.3.2",
      "source": "secalert@redhat.com",
      "tags": [
        "Patch"
      ]
    },
    {
      "url": "https://pypi.python.org/pypi/Pillow/2.5.2",
      "source": "secalert@redhat.com",
      "tags": [
        "Patch"
      ]
    },
    {
      "url": "http://lists.opensuse.org/opensuse-updates/2015-04/msg00056.html",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": []
    },
    {
      "url": "http://secunia.com/advisories/59825",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": []
    },
    {
      "url": "http://www.debian.org/security/2014/dsa-3009",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": []
    },
    {
      "url": "https://github.com/python-pillow/Pillow/commit/205e056f8f9b06ed7b925cf8aa0874bc4aaf8a7d",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Patch"
      ]
    },
    {
      "url": "https://pypi.python.org/pypi/Pillow/2.3.2",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Patch"
      ]
    },
    {
      "url": "https://pypi.python.org/pypi/Pillow/2.5.2",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Patch"
      ]
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T22:58:25.524088",
    "processing_status": "raw"
  }
}