{
  "cve_id": "CVE-2021-3514",
  "github_data": {
    "repository": "389ds/389-ds-base",
    "fix_commit": null,
    "related_commits": [],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": 6.5,
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "cwe_id": "CWE-476",
    "description": "When using a sync_repl client in 389-ds-base, an authenticated attacker can cause a NULL pointer dereference using a specially crafted query, causing a crash.",
    "attack_vector": "NETWORK",
    "attack_complexity": "LOW"
  },
  "temporal_data": {
    "published_date": "2021-05-28T15:15:09.253",
    "last_modified": "2024-11-21T06:21:43.637",
    "fix_date": null
  },
  "references": [
    {
      "url": "https://github.com/389ds/389-ds-base/issues/4711",
      "source": "secalert@redhat.com",
      "tags": [
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://lists.debian.org/debian-lts-announce/2023/04/msg00026.html",
      "source": "secalert@redhat.com",
      "tags": []
    },
    {
      "url": "https://github.com/389ds/389-ds-base/issues/4711",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://lists.debian.org/debian-lts-announce/2023/04/msg00026.html",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": []
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T23:01:57.128235",
    "processing_status": "raw"
  }
}