{
  "cve_id": "CVE-2019-25219",
  "github_data": {
    "repository": "chriskohlhoff/asio",
    "fix_commit": "93337cba7b013150f5aa6194393e1d94be2853ec",
    "related_commits": [
      "93337cba7b013150f5aa6194393e1d94be2853ec"
    ],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": 7.5,
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
    "cwe_id": "CWE-1188",
    "description": "Asio C++ Library before 1.13.0 lacks a fallback error code in the case of SSL_ERROR_SYSCALL with no associated error information from the SSL library being used.",
    "attack_vector": "NETWORK",
    "attack_complexity": "LOW"
  },
  "temporal_data": {
    "published_date": "2024-10-29T17:15:03.567",
    "last_modified": "2024-11-01T12:57:35.843",
    "fix_date": null
  },
  "references": [
    {
      "url": "https://github.com/chriskohlhoff/asio/commit/93337cba7b013150f5aa6194393e1d94be2853ec",
      "source": "cve@mitre.org",
      "tags": []
    },
    {
      "url": "https://github.com/chriskohlhoff/asio/compare/asio-1-12-2...asio-1-13-0",
      "source": "cve@mitre.org",
      "tags": []
    },
    {
      "url": "https://think-async.com/Asio/",
      "source": "cve@mitre.org",
      "tags": []
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T23:09:27.106785",
    "processing_status": "raw"
  }
}