{
  "cve_id": "CVE-2024-4343",
  "github_data": {
    "repository": "imartinez/privategpt",
    "fix_commit": "86368c61760c9cee5d977131d23ad2a3e063cbe9",
    "related_commits": [
      "86368c61760c9cee5d977131d23ad2a3e063cbe9"
    ],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": 9.8,
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    "cwe_id": "CWE-78",
    "description": "A Python command injection vulnerability exists in the `SagemakerLLM` class's `complete()` method within `./private_gpt/components/llm/custom/sagemaker.py` of the imartinez/privategpt application, versions up to and including 0.3.0. The vulnerability arises due to the use of the `eval()` function to parse a string received from a remote AWS SageMaker LLM endpoint into a dictionary. This method of parsing is unsafe as it can execute arbitrary Python code contained within the response. An attacker can exploit this vulnerability by manipulating the response from the AWS SageMaker LLM endpoint to include malicious Python code, leading to potential execution of arbitrary commands on the system hosting the application. The issue is fixed in version 0.6.0.",
    "attack_vector": "NETWORK",
    "attack_complexity": "LOW"
  },
  "temporal_data": {
    "published_date": "2024-11-14T18:15:19.687",
    "last_modified": "2024-11-18T21:35:08.590",
    "fix_date": null
  },
  "references": [
    {
      "url": "https://github.com/imartinez/privategpt/commit/86368c61760c9cee5d977131d23ad2a3e063cbe9",
      "source": "security@huntr.dev",
      "tags": []
    },
    {
      "url": "https://huntr.com/bounties/1d1e8f06-ec45-4b17-ae24-b83a41304c15",
      "source": "security@huntr.dev",
      "tags": []
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T23:09:29.298938",
    "processing_status": "raw"
  }
}