{
  "cve_id": "CVE-2024-48990",
  "github_data": {
    "repository": "liske/needrestart",
    "fix_commit": "fcc9a4401392231bef4ef5ed026a0d7a275149ab",
    "related_commits": [
      "fcc9a4401392231bef4ef5ed026a0d7a275149ab"
    ],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": 7.8,
    "cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    "cwe_id": "CWE-427",
    "description": "Qualys discovered that needrestart, before version 3.8, allows local attackers to execute arbitrary code as root by tricking needrestart into running the Python interpreter with an attacker-controlled PYTHONPATH environment variable.",
    "attack_vector": "LOCAL",
    "attack_complexity": "LOW"
  },
  "temporal_data": {
    "published_date": "2024-11-19T18:15:21.530",
    "last_modified": "2024-12-03T14:15:20.627",
    "fix_date": null
  },
  "references": [
    {
      "url": "https://github.com/liske/needrestart/commit/fcc9a4401392231bef4ef5ed026a0d7a275149ab",
      "source": "security@ubuntu.com",
      "tags": []
    },
    {
      "url": "https://www.cve.org/CVERecord?id=CVE-2024-48990",
      "source": "security@ubuntu.com",
      "tags": []
    },
    {
      "url": "https://www.qualys.com/2024/11/19/needrestart/needrestart.txt",
      "source": "security@ubuntu.com",
      "tags": []
    },
    {
      "url": "https://www.openwall.com/lists/oss-security/2024/11/19/1",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": []
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T23:09:31.267674",
    "processing_status": "raw"
  }
}